/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package register;

import static dbconnection.db.*;
import java.sql.*;

/**
 *
 * @author dhand
 */


public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
  
    public Dashboard() {
        initComponents();
        home.setVisible(true);
        panelBalance.setVisible(false);
        trackpro.setVisible(false);
        Connection c1 = null;
        Statement s1 = null;
        String s = "";
        ResultSet rs1 = null;
        try{
        c1 = DriverManager.getConnection("jdbc:mysql://instance-1.cnruxcy14rpo.us-east-1.rds.amazonaws.com/test",dbconnection.db.USER,dbconnection.db. PASS);
        s1 = c1.createStatement();
        String sq = "Select * from balance";
        rs1 = s1.executeQuery(sq);
        rs1.next();
        }catch(Exception e){System.out.println("Error in c1,s1,rs1,sq");}
        Integer i =0 ;
        try{
        i = rs1.getInt("bal");
        }catch(Exception e){System.out.println("Error in i to string");}
        String bala = i.toString();
        balance.setText(bala);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SellBut = new javax.swing.JButton();
        BuyBut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        TrackBut = new javax.swing.JButton();
        BalBut = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelBalance = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IncrBalance = new javax.swing.JSpinner();
        AddBalance = new javax.swing.JButton();
        trackpro = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        home = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 453, 18, 61));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        SellBut.setBackground(new java.awt.Color(204, 153, 0));
        SellBut.setText("<html><h2 ><b> Sell </b></h2></html>");
        SellBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SellBut.setContentAreaFilled(false);
        SellBut.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        SellBut.setOpaque(true);
        SellBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellButActionPerformed(evt);
            }
        });

        BuyBut.setBackground(new java.awt.Color(204, 153, 0));
        BuyBut.setText("<html><h2 ><b> Buy </b></h2></html>");
        BuyBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BuyBut.setContentAreaFilled(false);
        BuyBut.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        BuyBut.setOpaque(true);
        BuyBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyButActionPerformed(evt);
            }
        });

        TrackBut.setBackground(new java.awt.Color(204, 153, 0));
        TrackBut.setText("<html><h2 ><b> Track </b></h2></html>");
        TrackBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TrackBut.setContentAreaFilled(false);
        TrackBut.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TrackBut.setOpaque(true);
        TrackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrackButActionPerformed(evt);
            }
        });

        BalBut.setBackground(new java.awt.Color(204, 153, 0));
        BalBut.setText("<html><h2 ><b> Check Balance </b></h2></html>");
        BalBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BalBut.setContentAreaFilled(false);
        BalBut.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        BalBut.setOpaque(true);
        BalBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BalBut, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuyBut, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(SellBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(TrackBut, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BalBut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(BuyBut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TrackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SellBut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 514));

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 0, 720, -1));

        panelBalance.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("<html><h1><b> Current Balance </b></h1></html>");

        balance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        balance.setText("0");

        jLabel3.setText("<html><h1><b> Add Money </b></h1></html>");

        AddBalance.setBackground(new java.awt.Color(51, 102, 255));
        AddBalance.setForeground(new java.awt.Color(255, 255, 255));
        AddBalance.setText("<html><b>Add</h1></html>");
        AddBalance.setContentAreaFilled(false);
        AddBalance.setOpaque(true);
        AddBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBalanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBalanceLayout = new javax.swing.GroupLayout(panelBalance);
        panelBalance.setLayout(panelBalanceLayout);
        panelBalanceLayout.setHorizontalGroup(
            panelBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBalanceLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBalanceLayout.createSequentialGroup()
                        .addComponent(IncrBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(AddBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        panelBalanceLayout.setVerticalGroup(
            panelBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBalanceLayout.createSequentialGroup()
                .addGroup(panelBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBalanceLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBalanceLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(panelBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBalanceLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IncrBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        getContentPane().add(panelBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 97, -1, -1));

        trackpro.setPreferredSize(new java.awt.Dimension(720, 417));

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout trackproLayout = new javax.swing.GroupLayout(trackpro);
        trackpro.setLayout(trackproLayout);
        trackproLayout.setHorizontalGroup(
            trackproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trackproLayout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addGap(270, 270, 270))
        );
        trackproLayout.setVerticalGroup(
            trackproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trackproLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jRadioButton1)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        getContentPane().add(trackpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 97, 723, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Welcome, Order and manage your products all at one place .\\nGet Started by Adding balance from the Check balance Section");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 720, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SellButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellButActionPerformed
        // TODO add your handling code here:
      // jTextField1.setText("Hiiii");
      
        BuyBut.setText("<html><h2 style = \"color : black;\" ><b> Buy </b></h2></html>");
        TrackBut.setText("<html><h2 style = \"color : black;\" ><b> Track </b></h2></html>");
        SellBut.setText("<html><h2 style = \"color : red;\" ><b> Sell </b></h2></html>");
        BalBut.setText("<html><h2 style = \"color : black;\" ><b> Check Balance </b></h2></html>");

    }//GEN-LAST:event_SellButActionPerformed

    private void BuyButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyButActionPerformed
        // TODO add your handling code here:
   
        BuyBut.setText("<html><h2 style = \"color : red;\" ><b> Buy </b></h2></html>");
        TrackBut.setText("<html><h2 style = \"color : black;\" ><b> Track </b></h2></html>");
        SellBut.setText("<html><h2 style = \"color : black;\" ><b> Sell </b></h2></html>");
                BalBut.setText("<html><h2 style = \"color : black;\" ><b> Check Balance </b></h2></html>");

    }//GEN-LAST:event_BuyButActionPerformed

    private void TrackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrackButActionPerformed
        // TODO add your handling code here:
        panelBalance.setVisible(false);
        trackpro.setVisible(true);
         BuyBut.setText("<html><h2 style = \"color : black;\" ><b> Buy </b></h2></html>");
        TrackBut.setText("<html><h2 style = \"color : red;\" ><b> Track </b></h2></html>");
        SellBut.setText("<html><h2 style = \"color : black;\" ><b> Sell </b></h2></html>");
                BalBut.setText("<html><h2 style = \"color : black;\" ><b> Check Balance </b></h2></html>");

    }//GEN-LAST:event_TrackButActionPerformed

    private void BalButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalButActionPerformed
        // TODO add your handling code here:
        trackpro.setVisible(false);
        panelBalance.setVisible(true);
           BuyBut.setText("<html><h2 style = \"color : black;\" ><b> Buy </b></h2></html>");
        TrackBut.setText("<html><h2 style = \"color : black;\" ><b> Track </b></h2></html>");
        SellBut.setText("<html><h2 style = \"color : black;\" ><b> Sell </b></h2></html>");
        BalBut.setText("<html><h2 style = \"color : red;\" ><b> Check Balance </b></h2></html>");

    }//GEN-LAST:event_BalButActionPerformed

    private void AddBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBalanceActionPerformed
        // TODO add your handling code here:\
        Connection conn = null;
        Statement stmt = null;
        try{
            conn = DriverManager.getConnection(dbconnection.db.DB_URL,dbconnection.db.USER,dbconnection.db. PASS);
            stmt = conn.createStatement();

        }catch(Exception e)
        {
            System.out.print("Conn or Stmt Null");
        }
        String sql = "update  balance set bal = ";
        bal = Integer.parseInt(balance.getText());
        System.out.print(balance.getText());
        Integer it = (Integer)IncrBalance.getValue();
        it += bal;
        sql += it.toString() + " where id = 1";
        try{
            stmt.executeUpdate(sql);}catch(Exception e){System.out.println("Update fail");}
        String s = it.toString();
        balance.setText(s);

    }//GEN-LAST:event_AddBalanceActionPerformed
    private static Integer bal = 0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBalance;
    private javax.swing.JButton BalBut;
    private javax.swing.JButton BuyBut;
    private javax.swing.JSpinner IncrBalance;
    private javax.swing.JButton SellBut;
    private javax.swing.JButton TrackBut;
    private javax.swing.JLabel balance;
    private javax.swing.JPanel home;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelBalance;
    private javax.swing.JPanel trackpro;
    // End of variables declaration//GEN-END:variables
}
