/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package register;
import java.sql.*;
/**
 *
 * @author dhand
 */
   

public class stocksupdate extends javax.swing.JFrame {

     public static Connection c = Admin.c;
    public static void  updatestock(Connection c, Integer id, Integer quan)
    {
        String sql = "update buy set stock" + " = " + quan.toString() + " where id = " + id.toString();
        System.out.println(sql);
        Statement s = null;
        try{
            s = c.createStatement();
            s.executeUpdate(sql);
        }catch(Exception e){System.out.println("Error in stock update admin");}
    }
    
    /** Creates new form stocksupdate */
    public stocksupdate() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        ustock1 = new javax.swing.JSpinner();
        u1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        ustock2 = new javax.swing.JSpinner();
        u2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        ustock3 = new javax.swing.JSpinner();
        u3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        ustock4 = new javax.swing.JSpinner();
        u4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        ustock5 = new javax.swing.JSpinner();
        u5 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        ustock6 = new javax.swing.JSpinner();
        u6 = new javax.swing.JButton();
        u7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Stock Jeans");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 35, 101, 37));

        ustock1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        jPanel1.add(ustock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 115, 37));

        u1.setBackground(new java.awt.Color(102, 102, 255));
        u1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u1.setForeground(new java.awt.Color(255, 255, 255));
        u1.setText("Update");
        u1.setBorderPainted(false);
        u1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u1ActionPerformed(evt);
            }
        });
        jPanel1.add(u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 39, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 204, 204));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Stock Tshirt");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 101, 37));

        ustock2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        jPanel1.add(ustock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 115, 37));

        u2.setBackground(new java.awt.Color(102, 102, 255));
        u2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u2.setForeground(new java.awt.Color(255, 255, 255));
        u2.setText("Update");
        u2.setBorderPainted(false);
        u2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u2ActionPerformed(evt);
            }
        });
        jPanel1.add(u2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 204, 204));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Stock Shirt");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 101, 37));

        ustock3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        jPanel1.add(ustock3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 115, 37));

        u3.setBackground(new java.awt.Color(102, 102, 255));
        u3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u3.setForeground(new java.awt.Color(255, 255, 255));
        u3.setText("Update");
        u3.setBorderPainted(false);
        u3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u3ActionPerformed(evt);
            }
        });
        jPanel1.add(u3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 204, 204));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Stock Jacket");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 101, 37));

        ustock4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        jPanel1.add(ustock4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 115, 37));

        u4.setBackground(new java.awt.Color(102, 102, 255));
        u4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u4.setForeground(new java.awt.Color(255, 255, 255));
        u4.setText("Update");
        u4.setBorderPainted(false);
        u4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u4ActionPerformed(evt);
            }
        });
        jPanel1.add(u4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 204, 204));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Stock Hoodie");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 101, 37));

        ustock5.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        jPanel1.add(ustock5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 115, 37));

        u5.setBackground(new java.awt.Color(102, 102, 255));
        u5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u5.setForeground(new java.awt.Color(255, 255, 255));
        u5.setText("Update");
        u5.setBorderPainted(false);
        u5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u5ActionPerformed(evt);
            }
        });
        jPanel1.add(u5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 204, 204));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Stock Sweater");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 101, 37));

        ustock6.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        jPanel1.add(ustock6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 115, 37));

        u6.setBackground(new java.awt.Color(102, 102, 255));
        u6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u6.setForeground(new java.awt.Color(255, 255, 255));
        u6.setText("Update");
        u6.setBorderPainted(false);
        u6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u6ActionPerformed(evt);
            }
        });
        jPanel1.add(u6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        u7.setBackground(new java.awt.Color(102, 102, 255));
        u7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u7.setForeground(new java.awt.Color(255, 255, 255));
        u7.setText("Update All");
        u7.setBorderPainted(false);
        u7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u7ActionPerformed(evt);
            }
        });
        jPanel1.add(u7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void u1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u1ActionPerformed
        // TODO add your handling code here:
        Integer t = (Integer)ustock1.getValue();
        updatestock(c, 1, t);
    }//GEN-LAST:event_u1ActionPerformed

    private void u2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u2ActionPerformed
        // TODO add your handling code here:
          Integer t = (Integer)ustock2.getValue();
        updatestock(c, 2, t);
    }//GEN-LAST:event_u2ActionPerformed

    private void u3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u3ActionPerformed
        // TODO add your handling code here:
          Integer t = (Integer)ustock3.getValue();
        updatestock(c, 3, t);
    }//GEN-LAST:event_u3ActionPerformed

    private void u4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u4ActionPerformed
        // TODO add your handling code here:
          Integer t = (Integer)ustock4.getValue();
        updatestock(c, 4, t);
    }//GEN-LAST:event_u4ActionPerformed

    private void u5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u5ActionPerformed
        // TODO add your handling code here:
          Integer t = (Integer)ustock5.getValue();
        updatestock(c, 5, t);
    }//GEN-LAST:event_u5ActionPerformed

    private void u6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u6ActionPerformed
        // TODO add your handling code here:
          Integer t = (Integer)ustock1.getValue();
        updatestock(c, 6, t);
    }//GEN-LAST:event_u6ActionPerformed

    private void u7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u7ActionPerformed
        // TODO add your handling code here:
        Integer t1 = (Integer)ustock6.getValue();
        updatestock(c, 6, t1);
        Integer t2 = (Integer)ustock5.getValue();
        updatestock(c, 5, t2);
        Integer t3 = (Integer)ustock4.getValue();
        updatestock(c, 4, t3);
         Integer t4 = (Integer)ustock3.getValue();
        updatestock(c, 3, t4);
        Integer t5 = (Integer)ustock2.getValue();
        updatestock(c, 2, t5);
        Integer t6 = (Integer)ustock1.getValue();
        updatestock(c, 1, t6);   
    }//GEN-LAST:event_u7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stocksupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stocksupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stocksupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stocksupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stocksupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton u1;
    private javax.swing.JButton u2;
    private javax.swing.JButton u3;
    private javax.swing.JButton u4;
    private javax.swing.JButton u5;
    private javax.swing.JButton u6;
    private javax.swing.JButton u7;
    private javax.swing.JSpinner ustock1;
    private javax.swing.JSpinner ustock2;
    private javax.swing.JSpinner ustock3;
    private javax.swing.JSpinner ustock4;
    private javax.swing.JSpinner ustock5;
    private javax.swing.JSpinner ustock6;
    // End of variables declaration//GEN-END:variables

}
